version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: ${SERVERNAME:-think}-redis
      networks:
        - default

    mysql:
      image: daocloud.io/library/mysql:5.7
      container_name: ${SERVERNAME:-think}-mysql
      working_dir: /app
      volumes:
        - .:/app
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
      ports:
        - "8002:3306"
      networks:
        - default

    nginx:
      image: nginx:alpine
      container_name: ${SERVERNAME:-think}-nginx
      working_dir: /app
      volumes:
          - .:/app
          - ./nginx:/etc/nginx/conf.d
      ports:
        - "80:80"
      networks:
        - default

    php-fpm:
      build: ./php-fpm
      container_name: ${SERVERNAME:-think}-php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
      networks:
        - default

networks:
  default:

